vversion: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependencias y validando la fuente..."
  build:
    commands:
      - echo "Compilando archivos en CodeBuilder..."
  post_build:
    commands:
      - echo "Preparando los archivos para el almacenamiento en el Bucket de S3..."

artifacts:
  files:
    - 'pagina/**/*'
    - '.gitignore'